name: Flask App CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Especifique a versão do Python que você está usando

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instala as dependências do seu projeto

    - name: Run the Flask app
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}  # Referenciando o secret da chave de API do Google
      run: |
        echo "Using Google API Key"
        python app.py  # Substitua "app.py" pelo nome do seu arquivo principal do Flask
